version: '3.9'
services:
  web:
    build: .
    container_name: cicd-example
    ports:
      - '8085:8080'
    networks:
      - backend
networks:
  backend:
    driver: bridge
    name: backend_network
